image: docker:latest
services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  CONTAINER_IMAGE: talhibnerdocker/geni-vidi-vici:${CI_COMMIT_SHORT_SHA}

build:
  stage: build
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker build -t ${CONTAINER_IMAGE} .
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE}
    - docker tag ${CONTAINER_IMAGE} talhibnerdocker/geni-vidi-vici:latest
    - docker push ${CONTAINER_IMAGE}

deploy_staging:
  stage: deploy
  image: dtzar/helm-kubectl
  script:
    - kubectl config set-cluster k8s --server="${SERVER}"
    - kubectl config set clusters.k8s.certificate-authority-data ${CERTIFICATE_AUTHORITY_DATA}
    - kubectl config set-credentials gitlab --token="${USER_TOKEN}"
    - kubectl config set-context default --cluster=k8s --user=gitlab
    - kubectl config use-context default
    - sed -i "s/<VERSION>/${CI_COMMIT_SHORT_SHA}/g" webserver-deployment.yaml
    - kubectl apply -f webserver-deployment.yaml
    - kubectl apply -f webserver-service.yaml
    - kubectl get pods
    - kubectl get services
    - sleep 30s
    - kubectl get service webserver-httpd
    - echo "Please copy the service webserver's external-IP address above, and load the page in your browser to view it."
    - echo "Note! It might take several minutes for DNS to propagate and for your page to show up."